### PR TITLE
Prevents refractive index dispersions from being summed

### LINKED ISSUE #110: Conceptual problem of summing dispersions and refractive index
Problem: It is mathematically not allowed to sum dispersions if there is a conversion from n to eps somewhere, because
$$(n_1 + n_2)^2 \neq n_1^2 + n_2^2$$, the same applies for combinations for eps and n, where the situation is even more complicated since we cannot convert because either a part of n or eps is unknown due to a representation in the other imaginary plane.

Solution:

- Only allow adding of dispersions if they are natively written in eps.
- Add a flag to the dispersions whether they are represented in refr index or diel function and allow adding of refr index + conversion in DispersionSum

Follow up issue:

- Find out if there is a possible mathematical relation to add n and eps (kkr?).

### PR DESCRIPTION
**Pull request by domna**
Fixes #110 

Also keeps the DispersionSum flat, i.e. adds the dispersions to the internal DispersionSum list instead of creating `DispersionSum(DispersionSum(Dispersion, Dispersion), Dispersion`.

I think with this fix we could also release 0.15.1 to provide python 3.11 support and also to fix this bug in the published package.

### CODE REVIEW

**Comment by domna** [comment]
@MarJMue If you can come up with a better name than `UnsummableDispersion` I'm open. It sounds really weird to me but I could not think of something better 😅

**Comment by domna** [comment]
`NonAdditiveDispersion`? Sounds a bit weird, too...

Maybe it's weird because it is negating it. We could also switch and add additivity by an subclass with `AdditiveDispersion`, feels also a bit cleaner to me.

Edit: See #114

**Comment by domna** [comment]
I found a better way. I will implement it as `IndexDispersion` instead of `UnsummableDispersion`. In `IndexDispersion` only the refractive_index will be set and the dielectric_function will be calculated by a parent class method. This way we may also implement adding for n-based dispersions.

**Review by MarJMue — APPROVED** [review]
I think the implementation is good as is. And we can easily expand if needed. :+1:

**Pull request merged**
