### PR TITLE
Python 3.11 compatibility

### PR DESCRIPTION
**Pull request by domna**
With the release of python 3.11 I think it is time to check compatibility.

### CODE REVIEW

**Comment by domna** [comment]
h5py fails because it has no pre-build package for python 3.11, yet. To compile it on the server we would need to install the hdf5 library there and create an env variable. Albeit, I think this is generally possible to include this in the action and add an instruction for that, I think its just fine to wait for h5py 😎

**Comment by MarJMue** [comment]
I am in fact using 3.11 locally for the last couple of weeks. It works without any problems so far, except for the missing h5py wheel.

**Comment by domna** [comment]
Nice, so if h5py supplies it's wheels we can merge this I would say.
It's already on the way: https://github.com/h5py/h5py/pull/2165

**Comment by domna** [comment]
h5py 3.8.0 was released. We now can officially support python 3.11 🎉

**Review by MarJMue — APPROVED** [review]

**Pull request merged**
